@apiURL = https://vm2208.kaj.pouta.csc.fi:8432


GET {{apiURL}}/test

###
POST {{apiURL}}/test
Content-Type: application/json

{ "foo": "bar" }

###
PUT {{apiURL}}/test/123
Content-Type: application/json

{ "foo": "bar" }

###
DELETE {{apiURL}}/test/234234