@apiURL = https://fw-teaching.fi/demo/wdbocms/api/v1/products

### GET alla produkter

GET {{apiURL}}

### GET en produkt

GET {{apiURL}}/1001

### POST skapa en produkt
POST {{apiURL}}/
Content-Type: application/json

{
    "name": "Shoes",
    "price": 69.9
}

### PUT uppdatera en produkt
PUT {{apiURL}}/1002
Content-Type: application/json

{
    "name": "Fedora",
    "price": 50
}

### PATCH uppdatera enskilt fält i en produkt
PATCH {{apiURL}}/1001
Content-Type: application/json

{
    "price": 40.5
}

### DELETE radera en produkt
DELETE {{apiURL}}/1004