@apiURL = https://vm2208.kaj.pouta.csc.fi:8432


GET {{apiURL}}/test

###

GET {{apiURL}}/rooms/2

### POST skapa nytt rum
POST {{apiURL}}/rooms
Content-Type: application/json

{ 
    "number": 406, 
    "type": "double" 
}